name: Coverage
on:
    workflow_run:
        workflows: ["Build"]
        types:
          - completed
          
    pull_request:
        branches:
            - main
            - DOR*
            - feature/*
            - fix/*
jobs:
    coverage:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: ArtiomTr/jest-coverage-report-action@v2
              with:
                test-script: yarn jest
                package-manager: yarn
                working-directory: ./src
